### ISSUE TITLE
The React Preview server crashes

### ISSUE THREAD

**Issue by einarlove** [zenclabs/reactpreview#19]
**Describe the bug**v
The React Preview server crashes and won't start. This after a installing the extension and restarting VSCode

> The React Preview server crashed 5 times in the last 3 minutes. The server will not be restarted.

**To Reproduce**
Install the extension. Look down in the corner. Message from VSCode saying the server crashes and won't restart.

**Screenshots**
<img width="463" alt="image" src="https://user-images.githubusercontent.com/1495211/123409666-b99c8300-d5ae-11eb-9bca-54a3c56485c3.png">

**Extension logs (useful for crashes)**
Error: Cannot find module 'typescript'
Require stack:
- /Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.8519 (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:794421)
    at __webpack_require__ (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:794857)
    at Object.6810 (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:549479)
    at __webpack_require__ (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:794857)
    at Object.1031 (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:561507) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js'
  ]
}
[Info  - 12:07:08 PM] Connection to server got closed. Server will restart.
Error: Cannot find module 'typescript'
Require stack:
- /Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.8519 (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:794421)
    at __webpack_require__ (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:794857)
    at Object.6810 (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:549479)
    at __webpack_require__ (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:794857)
    at Object.1031 (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:561507) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js'
  ]
}
[Info  - 12:07:08 PM] Connection to server got closed. Server will restart.
Error: Cannot find module 'typescript'
Require stack:
- /Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.8519 (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:794421)
    at __webpack_require__ (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:794857)
    at Object.6810 (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:549479)
    at __webpack_require__ (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:794857)
    at Object.1031 (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:561507) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js'
  ]
}
[Info  - 12:07:08 PM] Connection to server got closed. Server will restart.
Error: Cannot find module 'typescript'
Require stack:
- /Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.8519 (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:794421)
    at __webpack_require__ (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:794857)
    at Object.6810 (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:549479)
    at __webpack_require__ (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:794857)
    at Object.1031 (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:561507) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js'
  ]
}
[Info  - 12:07:08 PM] Connection to server got closed. Server will restart.
Error: Cannot find module 'typescript'
Require stack:
- /Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.8519 (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:794421)
    at __webpack_require__ (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:794857)
    at Object.6810 (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:549479)
    at __webpack_require__ (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:794857)
    at Object.1031 (/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js:2:561507) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/einarlove/.vscode/extensions/zenclabs.reactpreview-0.2.2/dist/server/bundle.js'
  ]
}
[Error - 12:07:09 PM] Connection to server got closed. Server will not be restarted.

**Desktop (please complete the following information):**
 - OS: Macbook 13" M1
 - Extension version: 0.2.2

**Comment by fwouts** [comment]
Hey all, the install process should be a lot more reliable in v0.2.3, which was just released.

Feel free to reopen if you experience this again!
