### ISSUE TITLE
Error using theme property with styled components

### ISSUE THREAD

**Issue by jos3s** [zenclabs/reactpreview#27]
**Describe the bug**
I'm using styled components in a project, but when using theme variables the react preview returns an error that the variable is undefined

**To Reproduce**
1. Go to component
2. Click on 'Open Card2 in React Preview'
3. See error

**Expected behavior**
I would expect React preview to be able to take the values ​​that were defined in my theme file and use them as properties for the styled components.

**Screenshots**
![image](https://user-images.githubusercontent.com/50359547/123453663-249d8800-d5b6-11eb-8027-110424eeb1e9.png)

**Preview logs (useful for rendering errors)**
Uncaught TypeError: Cannot read property 'textColor' of undefined

    at styled.div.theme.theme (styles.ts:12)
    at Ne (Keyframes.js:20)
    at e2.generateAndInjectStyles (isStaticRules.js:6)
    at Keyframes.js:20
    at Keyframes.js:20
    at O2 (Keyframes.js:20)
    at renderWithHooks (react-dom.development.js:14985)
    at updateForwardRef (react-dom.development.js:17044)
    at beginWork (react-dom.development.js:19098)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945)

logs.ts:6 The above error occurred in the <styled.div> component:

    at O2 (http://localhost:3120/preview/node_modules/.vite/styled-components.js?v=ae551d2b:1420:6)
    at Card (http://localhost:3120/preview/src/components/Card/index.tsx?t=1624637127447:19:21)
    at Card3
    at ComponentLoader (http://localhost:3120/preview/@id/__x00__virtual:c:/Users/maria/JOS3S/nlw06/nlw06-letmeask/__reactpreview_internal__/ComponentLoader.tsx:7:3)
    at ErrorBoundary (http://localhost:3120/preview/@id/__x00__virtual:c:/Users/maria/JOS3S/nlw06/nlw06-letmeask/__reactpreview_internal__/ErrorBoundary.tsx:9:5)
React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
(anonymous) @ logs.ts:6

logs.ts:6 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

    at ComponentLoader (http://localhost:3120/preview/@id/__x00__virtual:c:/Users/maria/JOS3S/nlw06/nlw06-letmeask/__reactpreview_internal__/ComponentLoader.tsx:7:3)

**Desktop (please complete the following information):**
 - Windows 10
 - Extension version: 2004

**Comment by fwouts** [comment]
Hi @jos3s! This sounds like you just need to set up a Wrapper component that provides the theme. See https://reactpreview.com/usage for more info. Let me know how you go!

**Comment by jos3s** [comment]
That was exactly it, thank you! @fwouts
