### ISSUE TITLE
Transform failed

### ISSUE THREAD

**Issue by TheAussieStew** [zenclabs/reactpreview#45]
### Describe the bug

When I edit an in line css style, this error pops up. It's solved by closing the preview window and reopening it.

### Reproduction

1. Paste this code into a new VSCode file Text.tsx

`const Test = () => {
	return <div style={{width: 30}}>
		Testing
	</div>
}`
2. Open the component in VSCode.
3. Position the cursor after the "30".
4. Backspace the "30" and replace with "20".
5. Error should pop up

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 1.40 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.0.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.58.2 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Browsers:
    Chrome: 93.0.4577.63
    Safari: 14.1.1
```

### Used Package Manager

yarn

### Extension logs (useful for crashes)

```shell
7:44:40 PM [vite] Internal server error: Transform failed with 1 error:
src/view/Portal.tsx:2:9: error: Expected identifier but found ","
      at failureErrorWithLog (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.4.2/dist/server/node_modules/esbuild/lib/main.js:1451:15)
      at /Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.4.2/dist/server/node_modules/esbuild/lib/main.js:1262:29
      at /Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.4.2/dist/server/node_modules/esbuild/lib/main.js:609:9
      at handleIncomingPacket (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.4.2/dist/server/node_modules/esbuild/lib/main.js:706:9)
      at Socket.readFromStdout (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.4.2/dist/server/node_modules/esbuild/lib/main.js:576:7)
      at Socket.emit (events.js:315:20)
      at Socket.EventEmitter.emit (domain.js:467:12)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
```

**Comment by fwouts** [comment]
Hey @TheAussieStew, thank you for the bug report! I think this bug is already fixed in the latest version, would you be update to v0.5.4? :)

**Comment by TheAussieStew** [comment]
Perfect! I'll check it out and see if that fixes it

**Comment by TheAussieStew** [comment]
Just tried it out, looks like it's fixed - awesome
