### ISSUE TITLE
Infinite Loading When Opening Extension

### ISSUE THREAD

**Issue by TheAussieStew** [zenclabs/reactpreview#47]
### Describe the bug

When I upgraded to 0.6.0 and open a component, I get the 3 dots pulsing indefinitely. Restarting VSCode doesn't seem to reliably solve the infinite loading issue (It worked once, but didn't work the other several times I tried). This issue seems to happen across multiple of my .tsx components, ranging from relatively simple to more complex.

### Reproduction

1. Create a simple test component
2. Use either the blue button or the text above a component to open React Preview
3. Bug should happen upon load

### React Preview version

v0.6.0

### System Info

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 123.39 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.0.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.60.1 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Browsers:
    Chrome: 93.0.4577.82
    Safari: 14.1.2
```

### Used Package Manager

yarn

### Extension logs (useful for crashes)

```shell
Bootstrapped successfully.
React Preview Server running at http://localhost:3140.
6:40:12 PM [vite] new dependencies found: react, react-dom, updating...
6:40:13 PM [vite] ✨ dependencies updated, reloading page...
6:40:14 PM [vite] new dependencies found: @material-ui/core/Paper, @material-ui/core, framer-motion, @mui/icons-material/Person, updating...
 > node_modules/@mui/icons-material/utils/createSvgIcon.js:13:21: error: Could not resolve "@mui/material/utils" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    13 │ var _utils = require("@mui/material/utils");
       ╵                      ~~~~~~~~~~~~~~~~~~~~~

6:40:17 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@mui/icons-material/utils/createSvgIcon.js:13:21: error: Could not resolve "@mui/material/utils" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    at failureErrorWithLog (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:1478:15)
    at /Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:1136:28
    at runOnEndCallbacks (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:926:63)
    at buildResponseToResult (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:1134:7)
    at /Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:1243:14
    at /Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:614:9
    at handleIncomingPacket (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:711:9)
    at Socket.readFromStdout (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:581:7)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
React Preview Server stopped.
React Preview Server running at http://localhost:3140.
10:36:27 AM [vite] new dependencies found: react, react-dom, updating...
10:36:27 AM [vite] ✨ dependencies updated, reloading page...
10:36:29 AM [vite] new dependencies found: @material-ui/core/Paper, @material-ui/core, framer-motion, @mui/icons-material/Person, updating...
 > node_modules/@mui/icons-material/utils/createSvgIcon.js:13:21: error: Could not resolve "@mui/material/utils" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    13 │ var _utils = require("@mui/material/utils");
       ╵                      ~~~~~~~~~~~~~~~~~~~~~

10:36:29 AM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@mui/icons-material/utils/createSvgIcon.js:13:21: error: Could not resolve "@mui/material/utils" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    at failureErrorWithLog (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:1478:15)
    at /Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:1136:28
    at runOnEndCallbacks (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:926:63)
    at buildResponseToResult (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:1134:7)
    at /Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:1243:14
    at /Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:614:9
    at handleIncomingPacket (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:711:9)
    at Socket.readFromStdout (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:581:7)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
10:39:03 AM [vite] hmr update /render.jsx?p=src%2Fcomponents%2FCard.tsx&c=DetailCard&d=JTdCJTdE&s=JTNDRGV0YWlsQ2FyZCUyMCUyRiUzRQ==&i=1
10:39:34 AM [vite] hmr update /render.jsx?p=src%2Fcomponents%2FCard.tsx&c=DetailCard&d=JTdCJTdE&s=JTNDRGV0YWlsQ2FyZCUyMCUyRiUzRQ==&i=1 (x2)
10:39:34 AM [vite] hmr update /render.jsx?p=src%2Fcomponents%2FCard.tsx&c=DetailCard&d=JTdCJTdE&s=JTNDRGV0YWlsQ2FyZCUyMCUyRiUzRQ==&i=1 (x3)
```

### Preview logs (useful for rendering errors)

```shell
[Log] [vite] connecting... (preview, line 31)
[Log] [vite] connected. (preview, line 31)
[Error] SyntaxError: Importing binding name 'default' cannot be resolved by star export entries.
	link
	linkAndEvaluateModule
```

**Comment by TheAussieStew** [comment]
Actually I figured out the specific line of code that was preventing loading:

```
<PersonIcon/>
```
Imported as

```
import PersonIcon from '@mui/icons-material/Person';
```

Which appears to be related to this error:


```
10:55:55 AM [vite] new dependencies found: @material-ui/core/Paper, @material-ui/core, @mui/icons-material/Person, updating...
 > node_modules/@mui/icons-material/utils/createSvgIcon.js:13:21: error: Could not resolve "@mui/material/utils" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    13 │ var _utils = require("@mui/material/utils");
       ╵                      ~~~~~~~~~~~~~~~~~~~~~

10:55:56 AM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@mui/icons-material/utils/createSvgIcon.js:13:21: error: Could not resolve "@mui/material/utils" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    at failureErrorWithLog (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:1478:15)
    at /Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:1136:28
    at runOnEndCallbacks (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:926:63)
    at buildResponseToResult (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:1134:7)
    at /Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:1243:14
    at /Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:614:9
    at handleIncomingPacket (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:711:9)
    at Socket.readFromStdout (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.0/dist/server/node_modules/esbuild/lib/main.js:581:7)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
```

**Comment by fwouts** [comment]
Nice work! Would you be able to dump your `dependencies` here (especially versions of Material UI) so I can try to reproduce with the exact same version?

**Comment by fwouts** [comment]
Good news, I was able to reproduce the bug. Now let's see if I can fix it :)

**Comment by fwouts** [comment]
It appears you simply need to add `@mui/material` to your dependencies. It's a peer dependency of `@mui/icons-material`. Would you be able to try that out?

On my end, I'll make sure that these errors pop up in a more obvious way instead of a spinning loader :)

**Comment by TheAussieStew** [comment]
Whoops, didn't realise that @mui/material was different to the @material-ui/core I already had. I just added @mui/material and got this:

```
12:16:48 PM [vite] new dependencies found: @material-ui/core/Paper, @material-ui/core, framer-motion, @mui/icons-material/Person, updating...
 > node_modules/@mui/styled-engine/index.js:6:21: error: Could not resolve "@emotion/styled" (mark it as external to exclude it from the bundle)
    6 │ import emStyled from '@emotion/styled';
      ╵                      ~~~~~~~~~~~~~~~~~

 > node_modules/@mui/styled-engine/index.js:26:45: error: Could not resolve "@emotion/react" (mark it as external to exclude it from the bundle)
    26 │ export { ThemeContext, keyframes, css } from '@emotion/react';
       ╵                                              ~~~~~~~~~~~~~~~~

 > node_modules/@mui/styled-engine/StyledEngineProvider/StyledEngineProvider.js:3:30: error: Could not resolve "@emotion/react" (mark it as external to exclude it from the bundle)
    3 │ import { CacheProvider } from '@emotion/react';
      ╵                               ~~~~~~~~~~~~~~~~

 > node_modules/@mui/styled-engine/GlobalStyles/GlobalStyles.js:3:23: error: Could not resolve "@emotion/react" (mark it as external to exclude it from the bundle)
    3 │ import { Global } from '@emotion/react';
      ╵                        ~~~~~~~~~~~~~~~~

12:16:51 PM [vite] error while updating dependencies:
Error: Build failed with 4 errors:
node_modules/@mui/styled-engine/GlobalStyles/GlobalStyles.js:3:23: error: Could not resolve "@emotion/react" (mark it as external to exclude it from the bundle)
node_modules/@mui/styled-engine/StyledEngineProvider/StyledEngineProvider.js:3:30: error: Could not resolve "@emotion/react" (mark it as external to exclude it from the bundle)
node_modules/@mui/styled-engine/index.js:6:21: error: Could not resolve "@emotion/styled" (mark it as external to exclude it from the bundle)
node_modules/@mui/styled-engine/index.js:26:45: error: Could not resolve "@emotion/react" (mark it as external to exclude it from the bundle)
    at failureErrorWithLog (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.1/dist/server/node_modules/esbuild/lib/main.js:1478:15)
    at /Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.1/dist/server/node_modules/esbuild/lib/main.js:1136:28
    at runOnEndCallbacks (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.1/dist/server/node_modules/esbuild/lib/main.js:926:63)
    at buildResponseToResult (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.1/dist/server/node_modules/esbuild/lib/main.js:1134:7)
    at /Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.1/dist/server/node_modules/esbuild/lib/main.js:1243:14
    at /Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.1/dist/server/node_modules/esbuild/lib/main.js:614:9
    at handleIncomingPacket (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.1/dist/server/node_modules/esbuild/lib/main.js:711:9)
    at Socket.readFromStdout (/Users/conwayying/.vscode/extensions/zenclabs.reactpreview-0.6.1/dist/server/node_modules/esbuild/lib/main.js:581:7)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
```

**Comment by fwouts** [comment]
That's expected, I'm quite certain this is another peer dependency 🙂

**Comment by TheAussieStew** [comment]
Whoops 🤦 I've blamed what would usually be React errors on React Preview. Looks like a lot changed from MUI v4 to v5. Thanks! Issue is solved :)

**Comment by fwouts** [comment]
No worries, and thanks for reporting this, the next version will be much more helpful when these issues arise!

<img width="1440" alt="Screen Shot 2021-09-22 at 12 50 00 pm" src="https://user-images.githubusercontent.com/772570/134281559-58b636ee-cfdc-472f-ae24-6a0ef2a8c739.png">
