### ISSUE TITLE
Cannot find module 'typescript'

### ISSUE THREAD

**Issue by adamhill86** [zenclabs/reactpreview#9]
After installing this extension and opening a `.tsx` or `.jsx` file, VS Code shows the following alerts:

`A request has failed. See the output for more information. Source: React Preview (beta) (Extension)`

`The React Preview server crashed 5 times in the last 3 minutes. The server will not be restarted. Source: React Preview (beta) (Extension)`

Looking into the React Preview output, the following error is present 5 times:

```
Error: Cannot find module 'typescript'
Require stack:
- /Users/adamhill/.vscode/extensions/zenclabs.reactpreview-0.2.1/dist/server/bundle.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.8519 (/Users/adamhill/.vscode/extensions/zenclabs.reactpreview-0.2.1/dist/server/bundle.js:2:794199)
    at __webpack_require__ (/Users/adamhill/.vscode/extensions/zenclabs.reactpreview-0.2.1/dist/server/bundle.js:2:794635)
    at Object.6810 (/Users/adamhill/.vscode/extensions/zenclabs.reactpreview-0.2.1/dist/server/bundle.js:2:549479)
    at __webpack_require__ (/Users/adamhill/.vscode/extensions/zenclabs.reactpreview-0.2.1/dist/server/bundle.js:2:794635)
    at Object.1031 (/Users/adamhill/.vscode/extensions/zenclabs.reactpreview-0.2.1/dist/server/bundle.js:2:561507) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/adamhill/.vscode/extensions/zenclabs.reactpreview-0.2.1/dist/server/bundle.js'
  ]
}
```

This occurs consistently across multiple React/Next projects and reloading VS Code does not solve the issue. Let me know if you need any more details.

**Comment by fwouts** [comment]
Thank you @adamhill86 for the bug report!

When you first open it, React Preview installs a few packages including TypeScript. It sounds like that process didn't work in your case. Somehow it got stuck into a bad state.

Could you uninstall the extension, reload VS Code, then reinstall it, and see if there are any other errors at the very beginning of the logs?

If you're not sure how to re-open these logs, you can do `cmd-shift-p` -> Search Show Logs -> Extension Host, then switch to "React Preview" in the dropdown.

**Comment by adamhill86** [comment]
@fwouts Thanks. Uninstalling and reinstalling did the trick. It installed its packages correctly this time. Appreciate the assistance 👍

**Comment by fwouts** [comment]
Hi @adamhill86, the install process should be a lot more reliable in v0.2.3. Closing this now, but feel free to reopen if you find more issues!
